[project]
name = "nebula-project-telegram-bot"
version = "1.0.0"
description = "Nebula Project Telegram Bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.20.0.post0",
    "dishka>=1.5.3",
]
